language: node_js
node_js:
- '10'
services:
- docker
before_script:
- chmod -R +rwx ./devops
script:
- npm run test
before_deploy:
- "./devops/build_me.sh"
- "./devops/push_me.sh"
- "./devops/digital-ocean/before_deploy.sh"
deploy:
- provider: script
  skip_cleanup: true
  script: ssh -i travis_key -o StrictHostKeyChecking=no -tt $SSH_USER@$SSH_HOST "./run_cluster.sh"
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./devops/heroku/release_heroku.sh"
  on:
    branch: master
    tags: true
