language: node_js
node_js:
  - "10"
services:
  - docker

before_script:
  - chmod +x ./devops/build_me.sh
  - chmod +x ./devops/push_me.sh
  - sudo apt-get install -qq sshpass

script:
  - npm run test
  - sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -f -tt $SSH_USER@$SSH_HOST 'docker run -d --rm --env 'NODE_ENV=development' -p 8080:8080 igorlitv/fibo-server:latest'
