language: node_js
node_js:
- '10'
services:
- docker

before_script:
- chmod -R +rwx ./devops
- sudo apt-get install -qq sshpass
script:
- npm run test
- sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -tt $SSH_USER@$SSH_HOST "echo
  \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
before_deploy:
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- "./devops/build_me.sh"
- "./devops/push_me.sh"
- sshpass -p$SSH_PASS scp -o StrictHostKeyChecking=no -rp ./devops $SSH_USER@$SSH_HOST:/$SSH_USER/
- sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -tt $SSH_USER@$SSH_HOST "chmod
  +rwx ./devops/run_cluster.sh"
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
deploy:
- provider: script
  skip_cleanup: true
  script: sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -tt $SSH_USER@$SSH_HOST
    "./devops/run_cluster.sh"
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: "./devops/heroku/release_heroku.sh"
  on:
    branch: master
    tags: true
