language: node_js
node_js:
  - "10"
services:
  - docker

before_script:
  - chmod +x ./devops/build_me.sh
  - sudo apt-get install -qq sshpass

script:
  - npm run test
  - ./devops/build_me.sh
  - sshpass -p$SSH_PASS ssh -f -t -t -t $SSH_USER@$SSH_HOST $SSH_COMMAND
