language: node_js
node_js:
  - "10"
services:
  - docker

before_script:
  - chmod +x ./devops/build_me.sh
  - chmod +x ./devops/push_me.sh
  - chmod +x ./devops/run_me.sh
  - sudo apt-get install -qq sshpass

script:
  - npm run test
  - ./devops/build_me.sh
  - ./devops/push_me.sh
  - ./devops/run_me.sh
