language: node_js
node_js:
  - "10"
services:
  - docker

before_script:
  - chmod +x ./devops/build_me.sh
  - chmod +x ./devops/push_me.sh
  - sudo apt-get install -qq sshpass

script:
  - npm run test
  - ./devops/build_me.sh
  - ./devops/push_me.sh
  - sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -f -tt $SSH_USER@$SSH_HOST echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin&&docker run --rm --env 'NODE_ENV=development' -p 8080:8080 -it igorlitv/fibo-server:latest
