language: node_js
node_js:
  - "10"
services:
  - docker

before_script:
  - chmod +x ./devops/build_me.sh
  - chmod +x ./devops/push_me.sh
  - chmod +x ./devops/run_me.sh
  - sudo apt-get install -qq sshpass

script:
  - npm run test
deploy:
 provider: script
 skip_cleanup: true
 script: sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -f -tt $SSH_USER@$SSH_HOST "sudo docker stack deploy -c docker-compose.yml server_name"
 on:
   branch: feature/set-up-ci-with-ssh-keys
