language: node_js
node_js:
  - "10"
services:
  - docker

before_script:
  - chmod +x ./devops/build_me.sh
  - chmod +x ./devops/push_me.sh
  - chmod +x ./devops/run_me.sh
  - chmod +rwx ./devops
  - sudo apt-get install -qq sshpass

script:
  - npm run test
  - sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -f -tt $SSH_USER@$SSH_HOST "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
before_deploy:
  - sshpass -p$SSH_PASS scp -o StrictHostKeyChecking=no -rp ./devops $SSH_USER@$SSH_HOST:/$SSH_USER/
deploy:
 provider: script
 skip_cleanup: true
 script: sshpass -p$SSH_PASS ssh -o stricthostkeychecking=no -f -tt $SSH_USER@$SSH_HOST "cd /\"$SSH_USER\"/devops/ && sh /\"$SSH_USER\"/devops/run_cluster.sh"
 on:
   branch: feature/set-up-ci-with-ssh-keys
