name: DEPLOY-DEV

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Grant permissions
      run: chmod -R +rwx ./devops
    - name: Build a docker image
      run: sh ./devops/build_me.sh latest
    - name: Push a docker image to DockerHub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: sh ./devops/push_me.sh latest
    - name: Restore .ssh key from env variable
      env:
        SSH_CERT: ${{ secrets.SSH_CERT }}
      run: echo "$SSH_CERT" > ./travis_key    
    - name: Before deploy
      env:
        SSH_CERT: ${{ secrets.SSH_CERT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: sh ./devops/digital-ocean/before_deploy.sh